// Generated pixel art. Each character is one pixel; "." is transparent.
// Palette keys map to brand colours (see PALETTE).

export const PALETTE: Record<string, string> = {
  "K": "#04120c",
  "D": "#1b7a35",
  "G": "#34c253",
  "H": "#79f58a",
  "Y": "#c6f39c",
  "y": "#94d873",
  "S": "#0a0e10",
  "s": "#27343a",
  "W": "#e6f7ff",
  "M": "#06331b",
  "A": "#141c20",
  "a": "#2a3a42",
  "B": "#3b7bb5",
  "O": "#ffd43b",
  "I": "#d5dde0",
  "F": "#5cff72",
  "f": "#2cbf48",
  "b": "#f2ebdd",
  "c": "#b9b2a4",
  "g": "#3fcf4f",
  "h": "#27933a",
  "t": "#78ff86",
  "e": "#5a3b22",
  "E": "#3a2515",
  "r": "#744f2d",
};

/** Snake with sunglasses, laptop, flag and ball on a floating grass island. 48×40 */
export const MASCOT_SCENE: string[] = [
  "................................................",
  "..............................KKKKKKK...........",
  "............................KKHHHHHHHK..........",
  "..........................KKHHHGGGGHHHKK........",
  ".......................KKKHHGGGGGGGGGGHHKKK.....",
  "......................KSSssssssSSSSssssssSSK....",
  ".....................KSKSWWSSSSSSSSWWSSSSSKSK...",
  ".......KK.............KKSWSSSSSSGGSWSSSSSSKK....",
  "......KIFKK............KSSSSSSSSGGSSSSSSSSK.....",
  "......KIFFFKK...........KSSSSSSGGGGSSSSSSK......",
  "......KIFFFFFKK.........KGGGGGGGGGGGGGGGDK......",
  "......KIFFFFFFFK........KDGGGGGDGGDGGGGKDK......",
  "......KIfffffffK.........KDDGGGGGGGGGKKDK.......",
  "......KIfffffKK...........KKDDKKKKKKKDKK........",
  "......KIfffKK...............KKyYYyyK.K..........",
  "......KIfKK..................KGYYyGDK...........",
  "......KIK....................KDyYYGGK...........",
  "......KIK.....................KGYYGGHK..........",
  "......KIK.....................KDYYYGGHK.........",
  "......KIK......KKKKKKKKKKKKKK..KGYYYGGHK........",
  "......KIK.....KAAAAAAAAAAAAAAK.KDGYYYGGHK.......",
  "......KIK....KAAAAABBBAAAAAAK...KDGYYYGGDK......",
  "......KIK....KAAAABABBAAAAAAK....KDGYYYGGK......",
  "......KIK....KAAABBBBBOAAAAAK.....KDGYYGGDK.....",
  "......KIK....KAAABBBOOOOAAAAKKKKKKKKDYYYGDK.....",
  "......KIK...KAAAAAAOOOOOAAAHHHHHHHHHKGYYGDK.....",
  "......KIK...KAAAAAAOOAOAAAAGGGGGGGGGHGYYGDK.....",
  "......KIK.KKKAAAAAAAOOAAAAAGGGGGGGGGGGyYGGK.....",
  "......KIKKbbbAGGAAAAAAAAAAADDDDDDGGGGGGGGGDK....",
  "......tIKtbbbGGGGaaaaaaaaaaaaaKKKDDDGGGGGGDK....",
  ".....gtIgbcbbbGGGGGGKKKKKKKKKKgggKKKGGGGGGDK....",
  "...tgggIggbccDGGGGGGHHHHHHHHHHHHHHHHGGGGGGDKg...",
  "..gggggIgggggKDGGGGGGGGGGGGGGGGGGGGGGGGGGDKggt..",
  "...gggggggggggKDDDGGGGGGGGGGGGGGGGGGGGDDDKggg...",
  ".....hhhhhhhhhhKKKDDDDDDDGGGGGGDDDDDDDKKKhh.....",
  "....EEerehhhhhhhhhKKKKKKKDDDDDDKKKKKKKheeeEE....",
  "......EEEeEereeeehhhhhhhhKKKKKKeEreeeeeEEE......",
  ".........EEEEeeeereeeeeereeeEeereeeEEEE.........",
  ".............EEEEEeeeereEeeeerEEEEE.............",
  "..................EEEEEEEEEEEE..................",
];

/** Head only, for icons, favicons and small idle states. */
export const MASCOT_HEAD: string[] = MASCOT_SCENE.slice(0, 17).map((row) => row.slice(21, 45));
